# languages.py - Complete bilingual dictionary for Moslim Store
# Supports Arabic (ar) and English (en) perfectly

T = {
    "ar": {
        # ========== MAIN MENU & BASIC BUTTONS ==========
        "shop_now": "🛍️ تسوق الآن",
        "services": "🛒 الخدمات",
        "add_balance": "💰 إضافة رصيد",
        "profile": "👤 الملف الشخصي",
        "how_to_use": "📖 طريقة الاستخدام",
        "support": "📞 الدعم الفني",
        "proofs": "📢 إثباتات الثقة",
        "back_to_main": "🔙 العودة للقائمة الرئيسية",
        "back_to_sections": "🔙 العودة لأقسام المتجر",
        "back_to_ff_services": "🔙 العودة لخدمات فري فاير",
        "back_to_products": "🔙 العودة للمنتجات",
        "games_services": "🎮 خدمات الألعاب",
        "ff_services": "🕹️ خدمات فري فاير",
        "apps_service": "📱 اشتراكات التطبيقات",
        "ff_topup": "💎 شحن جواهر فري فاير",
        "keys_service": "🔑 إنشاء مفاتيح الهكرات",
        "back_to_games": "🔙 العودة لخدمات الألعاب",
        "social_media": "📢 خدمات سوشل ميديا",
        "proofs_button": "📢 قناة الإثباتات",
        "contact_manager": "💬 مراسلة المدير",
        "store_channel": "📢 قناة المتجر",
        "trust_proofs": "⭐ إثباتات الثقة",
        "contact_support_charge": "💳 مراسلة الدعم للشحن",
        "change_payment_button": "🔄 تغيير طريقة الدفع",
        "send_proof_button": "📸 أرسل الإيصال",

        # ========== GENERAL CHOICE MESSAGES ==========
        "choose_product": "🔍 *اختر نوع المنتج:*",
        "choose_validity": "📅 *اختر المدة:*",
        "choose_app": "🔍 *اختر التطبيق الذي تريده:*",
        "choose_payment": "💳 *اختر طريقة الدفع:*",
        "ask_proof": "📸 *أرسل صورة إثبات الدفع الآن*",
        "proof_received": "🔄 جاري معالجة طلبك... يرجى الانتظار.",
        "order_accepted": "✅ *تم قبول طلبك بنجاح!* ✅\n━━━━━━━━━━━━\n📦 المنتج: {}\n💰 السعر: {} درهم\n🔗 رابط التحميل: [اضغط هنا]({})\n📢 لمتابعة التحديثات: [انضم للقناة]({})\n━━━━━━━━━━━━\n📞 للاستفسار: [@MOSLIM_SHOP]({})\n📢 لمشاهدة إثباتاتنا: [اضغط هنا]({})",
        "order_rejected": "❌ *عذراً، تم رفض طلبك* ❌\n━━━━━━━━━━━━\n📦 المنتج: {}\n⚠️ يرجى التحقق من صحة إثبات الدفع وإعادة المحاولة.\n━━━━━━━━━━━━\n💡 يمكنك الضغط على الزر أدناه لتغيير طريقة الدفع.",
        "already_paid": "⚠️ لديك طلب قيد المراجعة بالفعل. يرجى الانتظار أو التواصل مع الدعم.",
        "keys_purchase_success": "✅ *تم الشراء بنجاح!* ✅\n━━━━━━━━━━━━\n📦 المنتج: {}\n🗓️ المدة: {} يوم\n💰 السعر: {} 💰\n🔑 مفتاحك: `{}`\n━━━━━━━━━━━━\n📞 للاستفسار: [@MOSLIM_SHOP]({})\n📢 لمشاهدة إثباتاتنا: [اضغط هنا]({})",
        "no_stock": "❌ عذراً، لا توجد مفاتيح متوفرة لهذه المدة حالياً.",
        "app_no_stock": "❌ هذا التطبيق غير متوفر حالياً. جرب تطبيقاً آخر.",
        "choose_section": "🛒 *أقسام المتجر:*\n━━━━━━━━━━━━\nاختر القسم المناسب:",
        "ff_packages_title": "💎 *باقات شحن جواهر فري فاير*\n━━━━━━━━━━━━\n✨ *باقات حصرية بأفضل الأسعار*\n⚡ *توصيل فوري خلال دقائق*\n━━━━━━━━━━━━\n*اختر الباقة المناسبة:*",

        # ========== VERIFICATION & ACTIVATION ==========
        "ask_password": "⚠️ *مـتـجـــر مـسـلـــم* 🛍️\nأدخل كلمة المرور لتفعيل المتجر:",
        "wrong_password": "❌ *كلمة مرور خاطئة!* ❌",
        "verified_success": "✅ *تم التفعيل بنجاح!* ✅\n🎉 مرحباً بك في متجر مسلم",
        "user_count": "\n👥 *عدد المستخدمين المسجلين:* {}",
        "welcome_main": "👋🏻 *أهلاً بك، {}!*\n\n🛍️ *في متجر مسلم - وجهتك الأولى للخدمات الحصرية*\n\n⭐ *أبرز مميزات المتجر:*\n🔑 خدمات رقمية مميزة / شحن فوري\n⚡ سرعة فائقة في التنفيذ\n🔒 متجر محمي وموثق 100%\n💸 أسعار لا تقبل المنافسة\n📢 *قناة الإثباتات:* [انقر هنا لمشاهدة الثقة]({})\n🚀 *اختر من القائمة بالأسفل لبدء التسوق!*",
        "profile_text": "👤 *ملفك الشخصي*\n━━━━━━━━━━━━\n🆔 المعرف: `{}`\n📅 تاريخ التسجيل: {}\n🛍️ *سجل مشترياتك:*\n{}\n━━━━━━━━━━━━\n📢 *شكراً لثقتك بنا* ❤️",
        "support_text": "👨‍💻 *فريق الدعم*\n━━━━━━━━━━━━\n• الرد خلال 24 ساعة\n• الدعم متوفر طوال الأسبوع\n• للمشاكل والاستفسارات\n━━━━━━━━━━━━\n*اختر طريقة التواصل:*",
        "add_balance_text": "💰 *إضافة رصيد*\n━━━━━━━━━━━━\n💵 *طرق الدفع المتاحة:*\n• CIH BANK\n• Binance (USDT)\n• PayPal\n• واتساب\n\n📌 *خطوات الشحن:*\n1️⃣ تواصل مع الدعم\n2️⃣ أرسل المبلغ المطلوب\n3️⃣ استلم الرصيد فوراً\n\n✨ *خدمة آمنة وسريعة*",
        "how_to_use_text": "📖 *طريقة الاستخدام*\n━━━━━━━━━━━━\n📌 *خطوات الشراء:*\n1️⃣ اختر الباقة المناسبة\n2️⃣ اضغط على زر الشراء\n3️⃣ اختر طريقة الدفع\n4️⃣ أرسل صورة الإثبات\n5️⃣ بعد الموافقة، استلم منتجك\n\n⚡ *شحن فوري - خدمة 24 ساعة*\n🔒 *ضمان استرجاع الأموال في حال وجود مشكلة*",
        "proofs_text": "📢 *قناة إثباتات الثقة والمصداقية*\n━━━━━━━━━━━━\n🔍 *شاهد بنفسك آراء العملاء السابقين:*\n✅ أكثر من 100+ عملية موثقة\n⭐ تقييم العملاء: ممتاز جداً\n\n[📢 اضغط هنا لمشاهدة الإثباتات]({})",
        "purchase_success": "✅ *تم الشراء بنجاح!* ✅\n━━━━━━━━━━━━\n💎 الكمية: {} جوهرة\n💰 السعر: {} درهم\n🔑 كود الشحن: `{}`\n━━━━━━━━━━━━\n📞 للاستفسار: [@MOSLIM_SHOP]({})\n📢 لمشاهدة إثباتاتنا: [اضغط هنا]({})",
        "out_of_stock": "❌ عذراً، هذه الباقة غير متوفرة حالياً. جرب باقة أخرى!",
        "confirm_purchase": "🎉 تم الشراء بنجاح! استلم الكود أعلاه",
        "welcome_after_lang": "🛍️ *مـتـجـــر مـسـلـــم | MOSLIM STORE* 🛍️\n━━━━━━━━━━━━━━━━━━━━\n✨ *خدمات رقمية - شحن فوري - اشتراكات* ✨\n⚡ *سرعة - ثقة - أسعار لا تقبل المنافسة* ⚡\n📢 *آراء العملاء:* [قناتنا مليئة بالإثباتات]({})\n━━━━━━━━━━━━━━━━━━━━\n🔓 *اضغط /start لتفعيل المتجر* 🔓",
        "default_reply": "🤖 *مرحباً!*\n━━━━━━━━━━━━\nاستخدم الأزرار بالأسفل للتنقل في المتجر.\n📢 وللتأكد من مصداقيتنا: [شاهد الإثباتات]({})",
        "inline_proofs_btn": "📢 قناة الإثباتات",
        "no_purchases": "📭 لا توجد مشتريات بعد.",

        # ========== SOCIAL MEDIA KEYS (hierarchical menus) ==========
        "social_choose_platform": "🌐 *اختر المنصة المطلوبة:*",
        "social_select_category": "📂 *اختر التصنيف:*",
        "social_select_subcategory": "📂 *اختر التصنيف الفرعي:*",
        "social_send_link": "🔗 *أرسل رابط الصفحة أو الملف الشخصي*\n\n📌 *مثال:* `https://www.example.com/username/posts/123456`",
        "social_send_quantity": "🔢 *أرسل الكمية المطلوبة* (رقم فقط):",
        "social_order_summary": "📋 *ملخص الطلب*\n━━━━━━━━━━━━\n📱 المنصة: {}\n📌 الخدمة: {}\n🔗 الرابط: {}\n🔢 الكمية: {}\n💰 السعر الإجمالي: {} درهم\n━━━━━━━━━━━━\n✅ لتأكيد الطلب: /confirm_social\n❌ للإلغاء: /cancel_social",
        "social_invalid_quantity": "❌ يرجى إدخال رقم صحيح للكمية (أكبر من 0).",
        "social_no_services": "⚠️ لا توجد خدمات متاحة حالياً.",
        "social_service_selected_error": "❌ الخدمة غير موجودة",
        "social_cancel_all": "❌ تم إلغاء جميع العمليات. يمكنك البدء من جديد.",
        "social_unknown_platform": "⚠️ منصة غير معروفة.",
        "social_no_categories": "⚠️ لا توجد تصنيفات متاحة.",
        "social_no_services_in_category": "⚠️ لا توجد خدمات في هذا التصنيف.",
        "social_api_success": "✅ *تم تنفيذ طلبك بنجاح!*\n🆔 رقم طلب API: `{}`\nيمكنك متابعة الحالة عبر /social_status {}",
        "social_api_fail": "❌ *فشل تنفيذ الطلب*\nالسبب: {}\nتم إبلاغ المدير.",
        "social_invalid_data": "❌ بيانات الطلب غير صالحة. تم إبلاغ المدير.",
        "social_internal_error": "❌ حدث خطأ داخلي. تم إبلاغ المدير.",
        "social_cancelled": "❌ تم إلغاء طلب السوشل ميديا.",
        "social_cancelled_all": "❌ تم إلغاء جميع العمليات. يمكنك البدء من جديد.",
        "social_no_pending_order": "⚠️ لا يوجد طلب قيد الانتظار للتأكيد. ابدأ باختيار خدمة من قسم السوشل ميديا.",
        "social_missing_data": "⚠️ البيانات ناقصة. يرجى إعادة اختيار الخدمة.",
        "social_order_created": "✅ *تم إنشاء طلب رقم `{}` بنجاح!*\n💰 المبلغ المطلوب: {} درهم.\n📱 المنصة: {}\n📌 الخدمة: {}\n\nالرجاء اختيار طريقة الدفع من القائمة أدناه.",
        "social_status_usage": "❗ الاستخدام: /social_status <api_order_id>",
        "social_status_invalid_id": "❌ معرف الطلب يجب أن يكون رقماً.",
        "social_status_title": "حالة الطلب",
        "status_label": "الحالة",
        "remains_label": "المتبقي",
        "start_count_label": "بدء العد",
        "social_status_fail": "❌ لم نتمكن من جلب حالة الطلب.",
        "social_confirm_prompt": "⚠️ يرجى تأكيد الطلب باستخدام /confirm_social أو إلغاؤه باستخدام /cancel_social",
        "social_quantity_error": "❌ حدث خطأ أثناء معالجة الكمية. حاول مرة أخرى.",
        "back_to_platforms_btn": "🔙 رجوع للمنصات",
        "back_to_categories_btn": "🔙 رجوع للتصنيفات",
        "back_btn": "🔙 رجوع",
        "choose_service": "اختر الخدمة:",
        "platform_label": "منصة:",
        "back_to_main_btn": "🔙 العودة للقائمة الرئيسية",

        # ========== GAMES & FF SPECIFIC ==========
        "choose_game": "🎮 *اختر اللعبة:*",
        "diamonds": "جوهرة",
        "mad_currency": "درهم",
        "see_proofs_before_buy": "شاهد الإثباتات قبل الشراء",
        "ff_menu_title": "🕹️ *خدمات فري فاير:*\n━━━━━━━━━━━━\nاختر الخدمة:",
        "ff_product_name": "جواهر فري فاير ({} جوهرة)",
        "key_product_name": "مفتاح DRIP CLIENT - {} يوم",
        "app_default": "تطبيق",
        "social_product_name": "خدمة سوشل ميديا",
        "unknown_product": "منتج غير معروف",
        "duration_label": "المدة",
        "days_label": "يوم",
        "update_channel_label": "قناة التحديثات",
        "app_delivered_success": "🎉 تم تسليم التطبيق بنجاح!",

        # ========== PAYMENT & ADMIN ==========
        "payment_method_label": "طريقة الدفع",
        "amount_label": "المبلغ",
        "order_id_label": "رقم الطلب",
        "payment_instruction": "بعد التحويل، أرسل صورة الإيصال بالضغط على الزر أدناه.",
        "cannot_change_payment": "لا يمكن تغيير طريقة الدفع الآن",
        "payment_changed": "✅ يمكنك اختيار طريقة دفع جديدة",
        "proof_not_photo": "❌ يرجى إرسال صورة وليس نصاً. أعد المحاولة.",
        "order_error": "❌ حدث خطأ في الطلب.",
        "new_payment_request": "طلب دفع جديد",
        "user_label": "المستخدم",
        "product_label": "المنتج",
        "payment_proof_label": "إثبات الدفع",
        "accept_order": "✅ قبول الطلب",
        "reject_order": "❌ رفض الطلب",
        "proof_received_admin": "📸 تم استلام إثبات الدفع! سيتم مراجعته من قبل الإدارة قريباً.",
        "not_allowed": "غير مسموح",
        "order_accepted_alert": "✅ تم قبول الطلب",
        "order_rejected_alert": "❌ تم رفض الطلب",
        "product_not_found": "❌ المنتج غير موجود",
    },

    "en": {
        # ========== MAIN MENU & BASIC BUTTONS ==========
        "shop_now": "🛍️ Shop Now",
        "services": "🛒 Services",
        "add_balance": "💰 Add Balance",
        "profile": "👤 Profile",
        "how_to_use": "📖 How to Use",
        "support": "📞 Support",
        "proofs": "📢 Trust Proofs",
        "back_to_main": "🔙 Back to Main Menu",
        "back_to_sections": "🔙 Back to Store Sections",
        "back_to_ff_services": "🔙 Back to Free Fire Services",
        "back_to_products": "🔙 Back to Products",
        "games_services": "🎮 Gaming Services",
        "ff_services": "🕹️ Free Fire Services",
        "apps_service": "📱 App Subscriptions",
        "ff_topup": "💎 Free Fire Diamonds Top-up",
        "keys_service": "🔑 Create Hacker Keys",
        "back_to_games": "🔙 Back to Games Services",
        "social_media": "📢 Social Media Services",
        "proofs_button": "📢 Proofs Channel",
        "contact_manager": "💬 Contact Manager",
        "store_channel": "📢 Store Channel",
        "trust_proofs": "⭐ Trust Proofs",
        "contact_support_charge": "💳 Contact Support for Payment",
        "change_payment_button": "🔄 Change Payment Method",
        "send_proof_button": "📸 Send Receipt",

        # ========== GENERAL CHOICE MESSAGES ==========
        "choose_product": "🔍 *Choose product type:*",
        "choose_validity": "📅 *Choose duration:*",
        "choose_app": "🔍 *Choose the app you want:*",
        "choose_payment": "💳 *Choose payment method:*",
        "ask_proof": "📸 *Send your payment proof screenshot now*",
        "proof_received": "🔄 Processing your order... Please wait.",
        "order_accepted": "✅ *Your order has been accepted!* ✅\n━━━━━━━━━━━━\n📦 Product: {}\n💰 Price: {} MAD\n🔗 Download link: [Click here]({})\n📢 For updates: [Join channel]({})\n━━━━━━━━━━━━\n📞 Inquiries: [@MOSLIM_SHOP]({})\n📢 See proofs: [Click here]({})",
        "order_rejected": "❌ *Sorry, your order has been rejected* ❌\n━━━━━━━━━━━━\n📦 Product: {}\n⚠️ Please check your payment proof and try again.\n━━━━━━━━━━━━\n💡 Press the button below to change payment method.",
        "already_paid": "⚠️ You have a pending order. Please wait or contact support.",
        "keys_purchase_success": "✅ *Purchase successful!* ✅\n━━━━━━━━━━━━\n📦 Product: {}\n🗓️ Duration: {} days\n💰 Price: {} 💰\n🔑 Your key: `{}`\n━━━━━━━━━━━━\n📞 Inquiries: [@MOSLIM_SHOP]({})\n📢 See our proofs: [Click here]({})",
        "no_stock": "❌ Sorry, no keys available for this duration.",
        "app_no_stock": "❌ This app is currently unavailable. Try another app.",
        "choose_section": "🛒 *Store Sections:*\n━━━━━━━━━━━━\nChoose the appropriate section:",
        "ff_packages_title": "💎 *Free Fire Diamonds Packages*\n━━━━━━━━━━━━\n✨ *Exclusive packages at best prices*\n⚡ *Instant delivery in minutes*\n━━━━━━━━━━━━\n*Choose your package:*",

        # ========== VERIFICATION & ACTIVATION ==========
        "ask_password": "⚠️ *MOSLIM STORE* 🛍️\nEnter password to activate the store:",
        "wrong_password": "❌ *Wrong password!* ❌",
        "verified_success": "✅ *Activated successfully!* ✅\n🎉 Welcome to Moslim Store",
        "user_count": "\n👥 *Registered users:* {}",
        "welcome_main": "👋🏻 *Welcome, {}!*\n\n🛍️ *Moslim Store - your first destination for exclusive services*\n\n⭐ *Store features:*\n🔑 Exclusive digital services / instant top-up\n⚡ High-speed execution\n🔒 100% protected and verified store\n💸 Unbeatable prices\n📢 *Proofs channel:* [Click here to see trust]({})\n🚀 *Choose from the menu below to start shopping!*",
        "profile_text": "👤 *Your Profile*\n━━━━━━━━━━━━\n🆔 ID: `{}`\n📅 Registration date: {}\n🛍️ *Your purchases:*\n{}\n━━━━━━━━━━━━\n📢 *Thank you for trusting us* ❤️",
        "support_text": "👨‍💻 *Support Team*\n━━━━━━━━━━━━\n• Response within 24 hours\n• Support available all week\n• For issues and inquiries\n━━━━━━━━━━━━\n*Choose contact method:*",
        "add_balance_text": "💰 *Add Balance*\n━━━━━━━━━━━━\n💵 *Payment methods available:*\n• CIH BANK\n• Binance (USDT)\n• PayPal\n• WhatsApp\n\n📌 *Steps to add:*\n1️⃣ Contact support\n2️⃣ Send the required amount\n3️⃣ Receive balance instantly\n\n✨ *Secure and fast service*",
        "how_to_use_text": "📖 *How to Use*\n━━━━━━━━━━━━\n📌 *Purchase steps:*\n1️⃣ Choose package\n2️⃣ Click buy\n3️⃣ Choose payment method\n4️⃣ Send proof screenshot\n5️⃣ After approval, receive product\n\n⚡ *24/7 support*\n🔒 *Money-back guarantee*",
        "proofs_text": "📢 *Trust and Credibility Proofs Channel*\n━━━━━━━━━━━━\n🔍 *See previous customers' reviews:*\n✅ 100+ documented transactions\n⭐ Customer rating: Excellent\n\n[📢 Click here to see proofs]({})",
        "purchase_success": "✅ *Purchase successful!* ✅\n━━━━━━━━━━━━\n💎 Quantity: {} diamonds\n💰 Price: {} MAD\n🔑 Top-up code: `{}`\n━━━━━━━━━━━━\n📞 Inquiries: [@MOSLIM_SHOP]({})\n📢 To see our proofs: [Click here]({})",
        "out_of_stock": "❌ Sorry, this package is currently unavailable. Try another package!",
        "confirm_purchase": "🎉 Purchase successful! Get your code above",
        "welcome_after_lang": "🛍️ *MOSLIM STORE* 🛍️\n━━━━━━━━━━━━━━━━━━━━\n✨ *Digital services - Instant top-up - Subscriptions* ✨\n⚡ *Speed - Trust - Unbeatable prices* ⚡\n📢 *Customer reviews:* [Our channel is full of proofs]({})\n━━━━━━━━━━━━━━━━━━━━\n🔓 *Press /start to activate the store* 🔓",
        "default_reply": "🤖 *Hello!*\n━━━━━━━━━━━━\nUse the buttons below to navigate the store.\n📢 To verify our credibility: [See proofs]({})",
        "inline_proofs_btn": "📢 Proofs Channel",
        "no_purchases": "📭 No purchases yet.",

        # ========== SOCIAL MEDIA KEYS ==========
        "social_choose_platform": "🌐 *Choose a platform:*",
        "social_select_category": "📂 *Select category:*",
        "social_select_subcategory": "📂 *Select subcategory:*",
        "social_send_link": "🔗 *Send your profile/page link*\n\n📌 *Example:* `https://www.example.com/username/posts/123456`",
        "social_send_quantity": "🔢 *Send quantity (number only):*",
        "social_order_summary": "📋 *Order Summary*\n━━━━━━━━━━━━\n📱 Platform: {}\n📌 Service: {}\n🔗 Link: {}\n🔢 Quantity: {}\n💰 Total price: {} MAD\n━━━━━━━━━━━━\n✅ Confirm: /confirm_social\n❌ Cancel: /cancel_social",
        "social_invalid_quantity": "❌ Please enter a valid quantity (greater than 0).",
        "social_no_services": "⚠️ No services available.",
        "social_service_selected_error": "❌ Service not found",
        "social_cancel_all": "❌ All operations canceled. You can start over.",
        "social_unknown_platform": "⚠️ Unknown platform.",
        "social_no_categories": "⚠️ No categories available.",
        "social_no_services_in_category": "⚠️ No services in this category.",
        "social_api_success": "✅ *Order placed successfully!*\n🆔 API Order ID: `{}`\nCheck status later using /social_status {}",
        "social_api_fail": "❌ *Order failed*\nReason: {}\nAdmin notified.",
        "social_invalid_data": "❌ Invalid order data. Admin notified.",
        "social_internal_error": "❌ Internal error. Admin notified.",
        "social_cancelled": "❌ Social media order cancelled.",
        "social_cancelled_all": "❌ All operations canceled. You can start over.",
        "social_no_pending_order": "⚠️ No pending order to confirm. Start by selecting a service from social media section.",
        "social_missing_data": "⚠️ Missing data. Please select service again.",
        "social_order_created": "✅ *Order #`{}` created!*\n💰 Amount: {} MAD.\n📱 Platform: {}\n📌 Service: {}\n\nPlease choose a payment method below.",
        "social_status_usage": "❗ Usage: /social_status <api_order_id>",
        "social_status_invalid_id": "❌ Order ID must be a number.",
        "social_status_title": "Order status",
        "status_label": "Status",
        "remains_label": "Remaining",
        "start_count_label": "Start count",
        "social_status_fail": "❌ Could not fetch order status.",
        "social_confirm_prompt": "⚠️ Please confirm the order using /confirm_social or cancel using /cancel_social",
        "social_quantity_error": "❌ Error processing quantity. Please try again.",
        "back_to_platforms_btn": "🔙 Back to platforms",
        "back_to_categories_btn": "🔙 Back to categories",
        "back_btn": "🔙 Back",
        "choose_service": "Choose service:",
        "platform_label": "Platform:",
        "back_to_main_btn": "🔙 Back to main menu",

        # ========== GAMES & FF SPECIFIC ==========
        "choose_game": "🎮 *Choose game:*",
        "diamonds": "diamonds",
        "mad_currency": "MAD",
        "see_proofs_before_buy": "See proofs before buying",
        "ff_menu_title": "🕹️ *Free Fire services:*\n━━━━━━━━━━━━\nChoose service:",
        "ff_product_name": "Free Fire diamonds ({} gems)",
        "key_product_name": "DRIP CLIENT key - {} days",
        "app_default": "App",
        "social_product_name": "Social media service",
        "unknown_product": "Unknown product",
        "duration_label": "Duration",
        "days_label": "days",
        "update_channel_label": "Update channel",
        "app_delivered_success": "🎉 App delivered successfully!",

        # ========== PAYMENT & ADMIN ==========
        "payment_method_label": "Payment method",
        "amount_label": "Amount",
        "order_id_label": "Order ID",
        "payment_instruction": "After transfer, send the receipt by pressing the button below.",
        "cannot_change_payment": "Cannot change payment method now",
        "payment_changed": "✅ You can choose a new payment method",
        "proof_not_photo": "❌ Please send a photo, not text. Try again.",
        "order_error": "❌ Order error.",
        "new_payment_request": "New payment request",
        "user_label": "User",
        "product_label": "Product",
        "payment_proof_label": "Payment proof",
        "accept_order": "✅ Accept order",
        "reject_order": "❌ Reject order",
        "proof_received_admin": "📸 Payment proof received! It will be reviewed by admin soon.",
        "not_allowed": "Not allowed",
        "order_accepted_alert": "✅ Order accepted",
        "order_rejected_alert": "❌ Order rejected",
        "product_not_found": "❌ Product not found",
    }
}
